//SCHEME: TWO-INPUT BUFFERS EACH OF SIZE N WITH SENTINEL CHARACTER "EOF" MARKING THE END OF EACH BUFFER
// "EOF" ALSO MARKS THE END OF INPUT

//PARAMETER N = NUMBER OF CHARACTERS READ WITH EACH RELOAD
int n = 10

//INPUT BUFFERS
int[] buffer_1;
