//SCHEME: TWO-INPUT BUFFERS EACH OF SIZE N WITH SENTINEL CHARACTER "EOF" MARKING THE END OF EACH BUFFER

//PARAMETER N = NUMBER OF CHARACTERS READ WITH EACH RELOAD

// EOF CHARACTERS AT END OF BOTH BUFFERS ALWAYS

// FUNCTIONS TO READ "RELOAD" INTO BUFFER FROM A FILE 

// CODE TO READ FROM THE BUFFERS CHARACTER BY CHARACTER