// MAKE A HASH TABLE AS THE SYMBOL TABL

// STORE LEXEMES IN A SEPARATE DATA STRUCTURE (?)

// ADD THE KEYWORDS <TOKEN, POINTER TO LEXEME>

// WRITE FUNCTIONS FOR INSERT (TOKEN, LEXEME) AND LOOKUP (LEXEME)
